from fpdf import FPDF

# Create a PDF class by inheriting from FPDF
class PDF(FPDF):
    def header(self):
        # Header implementation
        self.set_font('Arial', 'B', 12)
        self.cell(0, 10, 'My Document', 0, 1, 'C')

    def footer(self):
        # Footer implementation
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)

        # We show the credits
        self.cell(0, 10, 'Generated by Whatsapp Analyzer', 0, 0, 'L')

    def chapter_title(self, title):
        # Chapter title implementation
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, title, 0, 1, 'L')
        self.ln(5)

    def chapter_body(self, content):
        # Chapter body implementation
        self.set_font('Arial', '', 12)
        self.multi_cell(0, 10, content)
        self.ln()